using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AzRanger.Models.SharePoint
{
    public class SPOTenant
    {
        public string odatacontext { get; set; }
        public string odatatype { get; set; }
        public string odataid { get; set; }
        public string odataeditLink { get; set; }
        public string AIBuilderDefaultPowerAppsEnvironment { get; set; }
        public bool AIBuilderEnabled { get; set; }
        public int AIBuilderEnabledInContentCenter { get; set; }
        public object AIBuilderSiteListFileName { get; set; }
        public string AllOrganizationSecurityGroupId { get; set; }
        public int AllowAnonymousMeetingParticipantsToAccessWhiteboards { get; set; }
        public bool AllowAppsBypassOfUnmanagedDevicePolicy { get; set; }
        public bool AllowClassicPublishingSiteCreation { get; set; }
        public bool AllowCommentsTextOnEmailEnabled { get; set; }
        public bool AllowDownloadingNonWebViewableFiles { get; set; }
        public string[] AllowedDomainListForSyncClient { get; set; }
        public bool AllowEditing { get; set; }
        public bool AllowEveryoneExceptExternalUsersClaimInPrivateSite { get; set; }
        public bool AllowFileArchive { get; set; }
        public bool AllowFileArchiveOnNewSitesByDefault { get; set; }
        public bool AllowGuestUserShareToUsersNotInSiteCollection { get; set; }
        public bool AllowLegacyAuthProtocolsEnabledSetting { get; set; }
        public bool AllowLegacyBrowserAuthProtocolsEnabledSetting { get; set; }
        public bool AllowLimitedAccessOnUnmanagedDevices { get; set; }
        public bool AllowOverrideForBlockUserInfoVisibility { get; set; }
        public object AllowSelectSecurityGroupsInSPSitesList { get; set; }
        public object AllowSelectSGsInODBListInTenant { get; set; }
        public bool AllowSensitivityLabelOnRecords { get; set; }
        public bool AllowSharingOutsideRestrictedAccessControlGroups { get; set; }
        public bool AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled { get; set; }
        public string AmplifyAdminSettings { get; set; }
        public bool AnyoneLinkTrackUsers { get; set; }
        public object AppAccessInformationBarriersAllowList { get; set; }
        public bool AppBypassInformationBarriers { get; set; }
        public bool ApplyAppEnforcedRestrictionsToAdHocRecipients { get; set; }
        public bool AppOnlyBypassPeoplePickerPolicies { get; set; }
        public object ArchiveRedirectUrl { get; set; }
        public int AuthContextResilienceMode { get; set; }
        public bool AutofillColumnsEnabled { get; set; }
        public string AutofillColumnsSiteListFileName { get; set; }
        public bool BccExternalSharingInvitations { get; set; }
        public object BccExternalSharingInvitationsList { get; set; }
        public bool BlockAccessOnUnmanagedDevices { get; set; }
        public bool BlockAppAccessWithAuthenticationContext { get; set; }
        public object[] BlockDownloadFileTypeIds { get; set; }
        public bool BlockDownloadFileTypePolicy { get; set; }
        public int BlockDownloadLinksFileType { get; set; }
        public bool BlockDownloadOfAllFilesForGuests { get; set; }
        public bool BlockDownloadOfAllFilesOnUnmanagedDevices { get; set; }
        public bool BlockDownloadOfViewableFilesForGuests { get; set; }
        public bool BlockDownloadOfViewableFilesOnUnmanagedDevices { get; set; }
        public bool BlockMacSync { get; set; }
        public bool BlockSendLabelMismatchEmail { get; set; }
        public string BlockUserInfoVisibility { get; set; }
        public int BlockUserInfoVisibilityInOneDrive { get; set; }
        public int BlockUserInfoVisibilityInSharePoint { get; set; }
        public int BonusStorageQuotaMB { get; set; }
        public bool BusinessConnectivityServiceDisabled { get; set; }
        public bool ClassicPagesRestrictMode { get; set; }
        public bool CommentsOnFilesDisabled { get; set; }
        public bool CommentsOnListItemsDisabled { get; set; }
        public bool CommentsOnSitePagesDisabled { get; set; }
        public string CompatibilityRange { get; set; }
        public int ConditionalAccessPolicy { get; set; }
        public string ConditionalAccessPolicyErrorHelpLink { get; set; }
        public bool ContentSecurityPolicyConfigSynced { get; set; }
        public bool ContentSecurityPolicyEnforcement { get; set; }
        public object[] ContentTypeSyncSiteTemplatesList { get; set; }
        public int CoreBlockGuestsAsSiteAdmin { get; set; }
        public bool CoreDefaultLinkToExistingAccess { get; set; }
        public int CoreDefaultShareLinkRole { get; set; }
        public int CoreDefaultShareLinkScope { get; set; }
        public int CoreLoopDefaultSharingLinkRole { get; set; }
        public int CoreLoopDefaultSharingLinkScope { get; set; }
        public int CoreLoopSharingCapability { get; set; }
        public int CoreOrganizationSharingLinkMaxExpirationInDays { get; set; }
        public int CoreOrganizationSharingLinkRecommendedExpirationInDays { get; set; }
        public bool CoreRequestFilesLinkEnabled { get; set; }
        public int CoreRequestFilesLinkExpirationInDays { get; set; }
        public int CoreSharingCapability { get; set; }
        public string CustomizedExternalSharingServiceUrl { get; set; }
        public bool CustomScriptsRestrictMode { get; set; }
        public bool DataverseUsageConsentEnabled { get; set; }
        public object DefaultContentCenterSite { get; set; }
        public int DefaultLinkPermission { get; set; }
        public string DefaultODBMode { get; set; }
        public int DefaultSharingLinkType { get; set; }
        public bool DelayContentSecurityPolicyEnforcement { get; set; }
        public bool DelayDenyAddAndCustomizePagesEnforcement { get; set; }
        public bool DelayDenyAddAndCustomizePagesEnforcementOnClassicPublishingSites { get; set; }
        public bool DelegateRestrictedAccessControlConfiguration { get; set; }
        public bool DelegateRestrictedContentDiscoveryConfiguration { get; set; }
        public object DenySelectSecurityGroupsInSPSitesList { get; set; }
        public object DenySelectSGsInODBListInTenant { get; set; }
        public bool DisableAddToOneDrive { get; set; }
        public bool DisableBackToClassic { get; set; }
        public bool DisableCustomAppAuthentication { get; set; }
        public object DisabledAdaptiveCardExtensionIds { get; set; }
        public object[] DisabledModernListTemplateIds { get; set; }
        public bool DisableDocumentLibraryDefaultLabeling { get; set; }
        public object DisabledWebPartIds { get; set; }
        public bool DisableOutlookPSTVersionTrimming { get; set; }
        public bool DisablePersonalListCreation { get; set; }
        public bool DisableReportProblemDialog { get; set; }
        public bool DisableSharePointStoreAccess { get; set; }
        public bool DisableSpacesActivation { get; set; }
        public bool DisableVivaConnectionsAnalytics { get; set; }
        public bool DisallowInfectedFileDownload { get; set; }
        public bool DisplayNamesOfFileViewers { get; set; }
        public bool DisplayNamesOfFileViewersInSpo { get; set; }
        public bool DisplayStartASiteOption { get; set; }
        public bool DocumentUnderstandingEnabled { get; set; }
        public int DocumentUnderstandingEnabledInContentCenter { get; set; }
        public string DocumentUnderstandingSiteListFileName { get; set; }
        public bool EmailAttestationEnabled { get; set; }
        public int EmailAttestationReAuthDays { get; set; }
        public bool EmailAttestationRequired { get; set; }
        public bool EnableAIPIntegration { get; set; }
        public bool EnableAutoExpirationVersionTrim { get; set; }
        public bool EnableAutoNewsDigest { get; set; }
        public bool EnableAzureADB2BIntegration { get; set; }
        public bool EnabledFlightAllowAADB2BSkipCheckingOTP { get; set; }
        public bool EnableDirectToCustomerBilling { get; set; }
        public bool EnableDiscoverableByOrganizationForVideos { get; set; }
        public bool EnableGuestSignInAcceleration { get; set; }
        public bool EnableMediaReactions { get; set; }
        public bool EnableMinimumVersionRequirement { get; set; }
        public bool EnableMipSiteLabel { get; set; }
        public bool EnablePromotedFileHandlers { get; set; }
        public bool EnableRestrictedAccessControl { get; set; }
        public bool EnableSensitivityLabelForOneNote { get; set; }
        public bool EnableSensitivityLabelForPDF { get; set; }
        public bool EnableSensitivityLabelForVideoFiles { get; set; }
        public bool EnableSiteArchive { get; set; }
        public bool EnableTenantRestrictionsInsights { get; set; }
        public bool EnforceRequestDigest { get; set; }
        public string[] ESignatureAppList { get; set; }
        public bool ESignatureEnabled { get; set; }
        public object[] ESignatureSiteList { get; set; }
        public string[] ESignatureThirdPartyProviderInfoList { get; set; }
        public object[] ExcludedBlockDownloadGroupIds { get; set; }
        public string[] ExcludedFileExtensionsForSyncClient { get; set; }
        public bool ExemptNativeUsersFromTenantLevelRestricedAccessControl { get; set; }
        public int ExpireVersionsAfterDays { get; set; }
        public bool ExtendPermissionsToUnprotectedFiles { get; set; }
        public bool ExternalServicesEnabled { get; set; }
        public bool ExternalUserExpirationRequired { get; set; }
        public int ExternalUserExpireInDays { get; set; }
        public int FileAnonymousLinkType { get; set; }
        public bool FilePickerExternalImageSearchEnabled { get; set; }
        public string FileVersionPolicyXml { get; set; }
        public int FolderAnonymousLinkType { get; set; }
        public string GuestSharingGroupAllowListInTenant { get; set; }
        public object[] GuestSharingGroupAllowListInTenantByGroupId { get; set; }
        public object GuestSharingGroupAllowListInTenantByPrincipalIdentity { get; set; }
        public bool HardDeprecationRPSEnabled { get; set; }
        public bool HasAdminCompletedCUConfiguration { get; set; }
        public bool HasIntelligentContentServicesCapability { get; set; }
        public bool HasTopicExperiencesCapability { get; set; }
        public bool HideSyncButtonOnDocLib { get; set; }
        public bool HideSyncButtonOnODB { get; set; }
        public bool IBImplicitGroupBased { get; set; }
        public int ImageTaggingOption { get; set; }
        public string ImageTaggingSiteListFileName { get; set; }
        public bool IncludeAtAGlanceInShareEmails { get; set; }
        public bool InformationBarriersSuspension { get; set; }
        public string IPAddressAllowList { get; set; }
        public bool IPAddressEnforcement { get; set; }
        public int IPAddressWACTokenLifetime { get; set; }
        public bool IsAppBarTemporarilyDisabled { get; set; }
        public bool IsCollabMeetingNotesFluidEnabled { get; set; }
        public bool IsDataAccessInCardDesignerEnabled { get; set; }
        public bool IsEnableAppAuthPopUpEnabled { get; set; }
        public bool IsFluidEnabled { get; set; }
        public bool IsHubSitesMultiGeoFlightEnabled { get; set; }
        public bool IsLoopEnabled { get; set; }
        public bool IsMnAFlightEnabled { get; set; }
        public bool IsMultiGeo { get; set; }
        public bool IsMultipleHomeSitesFlightEnabled { get; set; }
        public bool IsMultipleVivaConnectionsFlightEnabled { get; set; }
        public bool IsUnmanagedSyncClientForTenantRestricted { get; set; }
        public bool IsUnmanagedSyncClientRestrictionFlightEnabled { get; set; }
        public bool IsVivaHomeFlightEnabled { get; set; }
        public bool IsVivaHomeGAFlightEnabled { get; set; }
        public bool IsWBFluidEnabled { get; set; }
        public bool KnowledgeAgentEnabled { get; set; }
        public int KnowledgeAgentScopeMode { get; set; }
        public string KnowledgeAgentSiteListFileName { get; set; }
        public object LabelMismatchEmailHelpLink { get; set; }
        public bool LegacyAuthProtocolsEnabled { get; set; }
        public bool LegacyBrowserAuthProtocolsEnabled { get; set; }
        public int LimitedAccessFileType { get; set; }
        public bool M365AdditionalStorageSPOEnabled { get; set; }
        public bool MachineLearningCaptureEnabled { get; set; }
        public int MajorVersionLimit { get; set; }
        public bool MarkAllFilesAsSensitiveByDefault { get; set; }
        public int MarkNewFilesSensitiveByDefault { get; set; }
        public bool MassDeleteNotificationDisabled { get; set; }
        public bool MassDeleteNotificationDisabledForODB { get; set; }
        public bool MassDeleteNotificationDisabledForSPO { get; set; }
        public int MediaTranscription { get; set; }
        public int MediaTranscriptionAutomaticFeatures { get; set; }
        public bool MobileFriendlyUrlEnabledInTenant { get; set; }
        public bool NewSharePointExperienceOptIn { get; set; }
        public object NoAccessRedirectUrl { get; set; }
        public bool NotificationsInOneDriveForBusinessEnabled { get; set; }
        public bool NotificationsInSharePointEnabled { get; set; }
        public bool NotifyOwnersWhenInvitationsAccepted { get; set; }
        public bool NotifyOwnersWhenItemsReshared { get; set; }
        public string OCRAdminSiteListFileName { get; set; }
        public string OCRComplianceSiteListFileName { get; set; }
        public int OCRModeForAdminSites { get; set; }
        public int OCRModeForComplianceODBs { get; set; }
        public int OCRModeForComplianceSites { get; set; }
        public int ODBAccessRequests { get; set; }
        public int ODBMembersCanShare { get; set; }
        public int ODBSensitivityRefreshWindowInHours { get; set; }
        public int ODBSharingCapability { get; set; }
        public bool ODBTranslationEnabled { get; set; }
        public bool OfficeClientADALDisabled { get; set; }
        public int OneDriveBlockGuestsAsSiteAdmin { get; set; }
        public bool OneDriveDefaultLinkToExistingAccess { get; set; }
        public int OneDriveDefaultShareLinkRole { get; set; }
        public int OneDriveDefaultShareLinkScope { get; set; }
        public bool OneDriveForGuestsEnabled { get; set; }
        public int OneDriveLoopDefaultSharingLinkRole { get; set; }
        public int OneDriveLoopDefaultSharingLinkScope { get; set; }
        public int OneDriveLoopSharingCapability { get; set; }
        public int OneDriveOrganizationSharingLinkMaxExpirationInDays { get; set; }
        public int OneDriveOrganizationSharingLinkRecommendedExpirationInDays { get; set; }
        public bool OneDriveRequestFilesLinkEnabled { get; set; }
        public int OneDriveRequestFilesLinkExpirationInDays { get; set; }
        public int OneDriveStorageQuota { get; set; }
        public bool OptOutOfGrooveBlock { get; set; }
        public bool OptOutOfGrooveSoftBlock { get; set; }
        public object OrgNewsSiteUrl { get; set; }
        public int OrphanedPersonalSitesRetentionPeriod { get; set; }
        public bool OwnerAnonymousNotification { get; set; }
        public bool PermissiveBrowserFileHandlingOverride { get; set; }
        public bool PrebuiltEnabled { get; set; }
        public int PrebuiltEnabledInContentCenter { get; set; }
        public string PrebuiltSiteListFileName { get; set; }
        public bool PreventExternalUsersFromResharing { get; set; }
        public bool ProvisionSharedWithEveryoneFolder { get; set; }
        public string PublicCdnAllowedFileTypes { get; set; }
        public bool PublicCdnEnabled { get; set; }
        public object[] PublicCdnOrigins { get; set; }
        public object ReactivationCost { get; set; }
        public int RecycleBinRetentionPeriod { get; set; }
        public bool ReduceTempTokenLifetimeEnabled { get; set; }
        public int ReduceTempTokenLifetimeValue { get; set; }
        public bool RequireAcceptingAccountMatchInvitedAccount { get; set; }
        public int RequireAnonymousLinksExpireInDays { get; set; }
        public float ResourceQuota { get; set; }
        public float ResourceQuotaAllocated { get; set; }
        public string RestrictedAccessControlForOneDriveErrorHelpLink { get; set; }
        public string RestrictedAccessControlforSitesErrorHelpLink { get; set; }
        public bool RestrictedOneDriveLicense { get; set; }
        public bool RestrictedSharePointLicense { get; set; }
        public object[] RestrictExternalSharing { get; set; }
        public bool RestrictExternalSharingForAgents { get; set; }
        public bool RestrictResourceAccountAccess { get; set; }
        public string RootSiteUrl { get; set; }
        public bool SearchResolveExactEmailOrUPN { get; set; }
        public bool SelfServiceSiteCreationDisabled { get; set; }
        public bool SharePointAddInsBlocked { get; set; }
        public bool SharePointAddInsDisabled { get; set; }
        public string SharingAllowedDomainList { get; set; }
        public string SharingBlockedDomainList { get; set; }
        public int SharingCapability { get; set; }
        public int SharingDomainRestrictionMode { get; set; }
        public bool ShowAllUsersClaim { get; set; }
        public bool ShowEveryoneClaim { get; set; }
        public bool ShowEveryoneExceptExternalUsersClaim { get; set; }
        public bool ShowNGSCDialogForSyncOnODB { get; set; }
        public bool ShowOpenInDesktopOptionForSyncedFiles { get; set; }
        public bool ShowPeoplePickerGroupSuggestionsForIB { get; set; }
        public bool ShowPeoplePickerSuggestionsForGuestUsers { get; set; }
        public string SignInAccelerationDomain { get; set; }
        public bool SiteOwnerManageLegacyServicePrincipalEnabled { get; set; }
        public bool SiteOwnersCanAccessMissingContent { get; set; }
        public bool SocialBarOnSitePagesDisabled { get; set; }
        public int SpecialCharactersStateInFileFolderNames { get; set; }
        public object SPJitDlpPolicyData { get; set; }
        public object StartASiteFormUrl { get; set; }
        public bool StopAlerts { get; set; }
        public bool StopNew2010Workflows { get; set; }
        public bool StopNew2013Workflows { get; set; }
        public int StorageQuota { get; set; }
        public int StorageQuotaAllocated { get; set; }
        public int StreamLaunchConfig { get; set; }
        public DateTime StreamLaunchConfigLastUpdated { get; set; }
        public int StreamLaunchConfigUpdateCount { get; set; }
        public bool SyncPrivacyProfileProperties { get; set; }
        public bool TaxonomyTaggingEnabled { get; set; }
        public string TaxonomyTaggingSiteListFileName { get; set; }
        public int TlsTokenBindingPolicyValue { get; set; }
        public bool TranslationEnabled { get; set; }
        public string TranslationSiteListFileName { get; set; }
        public bool UniversalAnnotationDisabled { get; set; }
        public bool UnlicensedOdbSyntexBillingEnabled { get; set; }
        public Unlicensedonedriveforbusinesstenantmetricsdata UnlicensedOneDriveForBusinessTenantMetricsData { get; set; }
        public bool UseFindPeopleInPeoplePicker { get; set; }
        public bool UsePersistentCookiesForExplorerView { get; set; }
        public object[] VersionPolicyFileTypeOverride { get; set; }
        public bool ViewersCanCommentOnMediaDisabled { get; set; }
        public bool ViewInFileExplorerEnabled { get; set; }
        public string WhoCanShareAllowListInTenant { get; set; }
        public object[] WhoCanShareAllowListInTenantByGroupId { get; set; }
        public object WhoCanShareAllowListInTenantByPrincipalIdentity { get; set; }
        public bool Workflow2010Disabled { get; set; }
        public int Workflows2013State { get; set; }
    }

    public class Unlicensedonedriveforbusinesstenantmetricsdata
    {
        public int adminLockedCount { get; set; }
        public float adminLockedSizeBytes { get; set; }
        public int billableCount { get; set; }
        public float billableSizeBytes { get; set; }
        public int complianceHoldCount { get; set; }
        public float complianceHoldSizeBytes { get; set; }
        public int count { get; set; }
        public int duplicateSiteCount { get; set; }
        public float duplicateSiteSizeBytes { get; set; }
        public int invalidLicenseCount { get; set; }
        public float invalidLicenseSizeBytes { get; set; }
        public DateTime lastRefreshOn { get; set; }
        public int restoredByTenantAdminCount { get; set; }
        public float restoredByTenantAdminSizeBytes { get; set; }
        public int retentionPeriodCount { get; set; }
        public float retentionPeriodSizeBytes { get; set; }
        public float sizeBytes { get; set; }
        public int unknownCount { get; set; }
        public float unknownSizeBytes { get; set; }
    }

}
